### ISSUE TITLE
Kernel 6.x - missed config CC_OPTIMIZE_FOR_PERFORMANCE_O3

### ISSUE THREAD

**Issue by Cerberios** [clang-musl-overlay/gentoo-patchset#17]
Hello there!
In Kernel 6.x is missed value: 
config CC_OPTIMIZE_FOR_PERFORMANCE_O3
Can You please look over and provide fix (patch) for enable -O3 level?
Thanks!

**Comment by capezotte** [comment]
You can use `make KCFLAGS=-O3` instead of relying on a patch.

[Kernel developers outright removed the config option](https://github.com/torvalds/linux/commit/a6036a41bffba3d5007e377483b425d470ad8042).
